#!/usr/bin/env bash

readonly DIR=/sys/class/power_supply

subscribe()
    while read -r line; do
        echo "$1 $line"
    done < <(battery -p "$DIR/BAT$1/")

# get a list of batteries
shopt -s nullglob

for battery in "$DIR/BAT"*; {
    batteries+=("${battery#*BAT}")
}

shopt -u nullglob

while read -r id capacity status; do
    printf -v "capacity_$id" '%s' "$capacity"
    printf -v "status_$id"   '%s' "$status"

    # get average battery level
    ((var = 0))

    for battery in "${batteries[@]}"; {
        tmp=capacity_$battery

        ((var += $((${!tmp}))))
    }

    ((var /= ${#batteries[@]}))

    # get appropriate icon
    for battery in "${batteries[@]}"; {
        tmp=status_$battery

        [[ ${!tmp} == Charging ]] && break
    } && icon= ||
        case $((var / 25)) in
            0) icon=;;
            1) icon=;;
            2) icon=;;
            3) icon=;;
            *) icon=
        esac

    echo "bat $icon%{O10}$var%%"
done < <(
    # subscribe to all batteries
    for battery in "${batteries[@]}"; {
        subscribe "$battery" &
    })
