#!/bin/sh

DIR=/sys/class/power_supply/BAT0

while :; do
    read -r sta < $DIR/status
    read -r var < $DIR/capacity

    [ "$sta" = Charging ] && icon= ||
        case $((var / 25)) in
            0) icon=;;
            1) icon=;;
            2) icon=;;
            3) icon=;;
            *) icon=
        esac

    echo "bat $icon $var%"

    sleep 10
done
