#!/bin/sh

while :; do
    read -r sta < /sys/class/power_supply/BAT0/status
    read -r var < /sys/class/power_supply/BAT0/capacity

    case $((var / 25)) in
        0) icon=;;
        1) icon=;;
        2) icon=;;
        3) icon=;;
        *) icon=
    esac

    [ "$sta" = Charging ] && icon=

    echo "bat $icon $var%"

    sleep 10
done
