#!/bin/sh

while :; do
    mpc | {
        IFS= read -r  title
        IFS= read -r status

        case $status in
            *playing*)
                # shorten title if necessary
                [ $((${#title} > 45)) -eq 1 ] &&
                    title=$(printf '%.45s...' "$title")
                ;;
            *) title='Not Playing'
        esac

        printf 'mus %%{O10}%s\n' "$title"
    }

    mpc idle player
done
