#!/bin/sh

while :; do
    mpc | {
        read -r var
        read -r sta

        case $sta in
            *playing*)
                [ ${#var} -gt 50 ] &&
                    # shorten current song title
                    var=$(printf '%.50s...' "$var")
                ;;
            *) var='Not Playing'
        esac

        echo "mus  $var"
    }

    mpc idle player
done
