#!/bin/sh

_() printf '%s\n' "ntw %{O10}$1"

# ensure network block isn't empty on startup
{ echo 'default via'; ip monitor route dev wlan0; } |
    while read -r event; do
        case $event in
            'default via'*)
                var=$(iwgetid -r)

                _ "${var:-Disconnected}"
                ;;
            'Deleted default via'*)
                _ 'Disconnected'
                ;;
            *) continue
        esac
    done
