#!/bin/sh

readonly FILE=~/.local/share/todo

# ensure todo block isn't empty on startup
{ echo; wendy -m 2056 -w "$FILE" -v; } |
    while read -r _; do
        # get number of entries
        : $((cnt = 0))

        while read -r line; do
            : $((cnt += 1))
        done < $FILE

        printf '%s\n' "tdl %{O10}$cnt"
    done
