#!/bin/sh

FILE=~/.local/share/todo

# ensure todo block isn't empty on startup
{ echo; wendy -vm 2056 -w "$FILE"; } |
    while read -r event; do
        # get number of entries
        cnt=0

        while read -r line; do
            cnt=$((cnt + 1))
        done < "$FILE"

        echo "tdl %{O10}$cnt"
    done
