#!/bin/sh

while :; do
    # ensure volume module isn't empty on startup
    { echo; stdbuf -oL alsactl monitor; } |
        while read -r _; do
            out=$(amixer get Master)

            case $out in
                *'[on]')  icon=;;
                *'[off]') icon=;;
            esac

            out=${out%%%]*}
            out=${out#*[}%

            printf 'vol %s%%{O10}%s\n' "$icon" "$out"
        done
done
