#!/bin/sh

readonly SINK=0

# ensure volume module isn't empty on startup
{ echo "Event 'change' on sink #$SINK"; pactl subscribe; } |
    while read -r event; do
        case $event in
            "Event 'change' on sink #$SINK")
                {
                    pactl get-sink-volume "$SINK"
                    pactl get-sink-mute   "$SINK"
                } | {
                    read -r _ _ _ _ volume _
                    read -r _
                    read -r _ status

                    case $status in
                        no)  icon=;;
                        yes) icon=;;
                    esac

                    printf '%s\n' "vol $icon%{O10}$volume%"
                }
        esac
    done
