#!/bin/sh

# ensure volume module isn't empty on startup
{ echo "Event 'change' on sink #"; pactl subscribe; } |
    while read -r event; do
        case $event in
            "Event 'change' on sink #"*)
                sink=$(pactl get-default-sink)

                {
                    pactl get-sink-volume "$sink"
                    pactl get-sink-mute   "$sink"
                } | {
                    read -r _ _ _ _ volume _
                    read -r _
                    read -r _ status

                    case $status in
                        no)  icon=;;
                        yes) icon=;;
                    esac

                    printf '%s\n' "vol $icon%{O10}$volume%"
                }
        esac
    done
