#!/bin/sh

# ensure workspaces block isn't empty on startup
{ echo; xtitle -s; } |
    while read -r win; do
        win=${win:-Desktop} # fallback
        cur=$(bspc query -D -d --names)

        var="$cur - $win"

        # shorten current window title
        [ ${#var} -gt 45 ] &&
            var=$(printf '%.45s...' "$var")

        printf '%s\n' "wks %{O10}$var"
    done
