#!/bin/sh

xtitle -s |
    while read -r win; do
        win=${win:-Desktop} # fallback
        cur=$(bspc query -D -d --names)

        var="$cur - $win"

        # shorten current window title
        [ ${#var} -gt 45 ] &&
            var=$(printf '%.45s...' "$var")

        echo "wks   $var"
    done
