#!/bin/sh

die() {
    echo "${1:-usage : ${0##*/} <laptop|termux|server>}" >&2
    exit 1
}

type stow > /dev/null 2>&1 ||
    die 'error : install stow first'

_()
    stow -t ~ "$@"

case $1 in
    laptop) _ alacritty chicken dunst fonts git gtk misc mpv music rofi shell ssh vim wm x;;
    termux) _ chicken misc shell ssh termux vim;;
    server) _ chicken misc shell ssh vim;;
    *)
        die
esac
