#!/bin/sh

_() {
    pgrep -x "$1" > /dev/null ||
        { "$@" & }
}

readonly XRES_FILE=~/.config/xres/main
readonly FONTS_DIR=~/.local/share/fonts

# settings
setxkbmap -option caps:swapescape
xsetroot -cursor_name left_ptr
xset s off -dpms

# daemons
_ dunst
_ mpd
_ sxhkd -m 1

# rice
[ -f "$FONTS_DIR/fonts.dir" ] &&
    xset +fp "$FONTS_DIR"

[ -f "$XRES_FILE" ] &&
    xrdb -merge "$XRES_FILE"

wallpaper

# wm
pgrep -x bspwm > /dev/null ||
    exec bspwm > /dev/null 2>&1
