#!/bin/sh

# settings
setxkbmap fr -option caps:swapescape
xsetroot -cursor_name left_ptr
xset s off -dpms

# daemons
_() {
    pgrep -x "$1" > /dev/null ||
        { "$@" & }
}

_ bat-monitor
_ dunst
_ mpd
_ sxhkd -m 1

# rice
tmp=~/.local/share/fonts

[ -f "$tmp/fonts.dir" ] &&
    xset +fp "$tmp"

tmp=~/.config/xres/main

[ -f "$tmp" ] &&
    xrdb -merge "$tmp"

tmp=~/.config/setroot/.setroot-restore

[ -x "$tmp" ] &&
    setroot --restore

# wm
bspc query -M > /dev/null 2>&1 ||
    exec bspwm

# vim: ft=sh
