#!/bin/sh

readonly XRES_FILE=~/.config/xres/main
readonly FONTS_DIR=~/.local/share/fonts

_() pidof "$1" > /dev/null

# daemons
_ dbus-launch ||
    eval "$(
        dbus-launch     \
            --sh-syntax \
            --exit-with-x11
    )"

_ pulseaudio      || { pulseaudio --start --exit-idle-time=-1; }
_ battery_monitor || { battery_monitor & }
_ dunst           || { dunst & }
_ mpd             || { mpd; }
_ mpd-mpris       || { mpd-mpris & }
_ playerctld      || { playerctld & }
_ sxhkd           || { sxhkd -m 1 & }

# settings
xsetroot -cursor_name left_ptr
xset s off -dpms
xrandr --dpi 96

[ -f "$FONTS_DIR/fonts.dir" ] &&
    xset +fp "$FONTS_DIR"

[ -f "$XRES_FILE" ] &&
    xrdb -merge "$XRES_FILE"

wallpaper

# wm
_ bspwm ||
    exec bspwm > /dev/null 2>&1
