#!/bin/sh
#
# xinitrc

# daemons
sxhkd -m1 &
dunst &
mpd &

# settings
setxkbmap fr -option caps:swapescape
xsetroot -cursor_name left_ptr
xset s off -dpms

# rice
xset +fp ~/.local/share/fonts
xrdb -merge ~/.config/xres/main
setroot --restore

# wm
exec bspwm
