#!/bin/sh
#
# teleport cursor

{ wattr xywh "$(pfw)"; wmp; } |
{
    read -r x y w h; read -r mx my

    # exit if the cursor is already on the window
    [ "$mx" -ge "$x" ] && [ "$mx" -le "$((x + w))" ] &&
    [ "$my" -ge "$y" ] && [ "$my" -le "$((y + h))" ] && exit

    x=$((x + w / 2))
    y=$((y + h / 2))

    wmp "$x" "$y"
}
