#!/bin/sh
#
# properly exit bspwm

# clean up utilities
for bin in borders panel; do
    pkill -x "$bin"
done

# save state before reload
if [ "$1" -eq 0 ]; then
    bspc wm -d > /tmp/bspwm.json
fi

bspc quit "$1"
