#!/bin/sh
#
# bspwm config

# SETTINGS

bspc monitor -d 1 2 3 4 5

bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc config border_width 5
bspc config window_gap 5

bspc config normal_border_color \#CCCCCC
bspc config focused_border_color \#555555
bspc config presel_feedback_color \#EEEEEE

bspc config split_ratio 0.5

bspc config external_rules_command "$(which rules)"

# UTILS

sxhkd &
bar &
