#!/bin/sh
#
# bspwm config

# SETTINGS

bspc monitor -d 1 2 3 4 5

bspc config focus_follows_pointer true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config click_to_focus true

bspc config border_width 7
bspc config window_gap 7

bspc config normal_border_color \#032C36
bspc config focused_border_color \#EEEEEE
bspc config presel_feedback_color \#EEEEEE

bspc config split_ratio 0.5

# UTILS

bspc config external_rules_command "$(which rules)"

pgrep -x bar > /dev/null || bar &
