#!/bin/sh
#
# mpd control

{
    # exit if mpd isn't running
    pgrep -x mpd && mpc "$1" || exit
} \
    > /dev/null

case $1 in
    toggle) exit;;
    *)
        # send a notification when fullscreen
        if bspc query -N -n focused.fullscreen > /dev/null; then
            dunstify -r 550 "$(mpc current)"
        fi
esac
