#!/bin/sh
#
# volume control

case $1 in
    # argument parsing
    +) arg=increase;;
    -) arg=decrease;;
    toggle)
        ponymix toggle > /dev/null
        exit
esac

var=$(ponymix "$arg" "$2")

# send a notification when fullscreen
bspc query -N -n focused.fullscreen > /dev/null &&
    dunstify -r 500 "Volume : $var%"
