#!/bin/sh
#
# volume control

case $1 in
    # pattern matching
    +*) arg=increase;;
    -*) arg=decrease;;
    toggle)
        ponymix toggle > /dev/null
        exit
esac

var=$(ponymix "$arg" "${1#?}")

# send a notification when fullscreen
if bspc query -N -n focused.fullscreen > /dev/null &&
    dunstify -r 500 "Volume : $var%"
fi
